module.exports = {
	docs: [
		"intro",
		"getting-started",
		{
			type: "category",
			label: "Core concepts",
			collapsed: false,
			items: [
				"concepts/rendering",
				"concepts/state",
				"concepts/lifecycle",
			],
		},
		{
			type: "category",
			label: "Guides",
			collapsed: false,
			items: [
				"guides/performance",
				"guides/examples",
			],
		},
		{
			type: "category",
			label: "API",
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "api",
				},
			],
		},
		{
			type: "category",
			label: "Reference",
			collapsed: true,
			items: [
				"reference/moonwave-authoring",
			],
		},
	],
};
